### ISSUE TITLE
Assert::false and Assert::true should have a message

### ISSUE THREAD

**Issue by paulovitorbal** [mollie/php-coding-standards#7]
I was discussing this with my team, should I create a rule that guarantee that `Assert::true` and `Assert::false` have a message, so we stop progagating: `We expected true, got false`?

what do you think?

**Comment by dmvdbrugge** [comment]
Question: As this repo currently only uses PHP-CS-Fixer and not for example PHP_CodeSniffer, every rule should not lint but fix. What would your rule fix this into that makes it better than the default?

Furthermore I'm not sure if we actually want to add custom fixers (especially when related to very specific other packages) to this generic package.

**Comment by dmvdbrugge** [comment]
Closing, because proposed is a lint, not a fix.
